#+TITLE: 10 Design Patterns
#+AUTHOR: Rahul M. Juliato

A study on 10 design patterns using Typescript

* Creational
How objects are created
** Singleton
A type of object that can only be instantiated **once**.
#+BEGIN_SRC typescript
  class Settings {
    static instance: Settings;


    // prevent new with private constructor
    private constructor() {

    }

    static getInstance(): Settings {
      if(!Settings.instance) {
	Settings.instance = new Settings();
      }

      return Settings.instance;
    }
  }

  // const settings = new Settings()
  const settings = Settings.getInstance();
#+END_SRC

Obs: in javascript we have object literals and also the concept of
global data and objects are passed around by reference. We get
basically the same caracteristics of this pattern by simply creating a
global object, such as:

#+BEGIN_SRC typescript
  const settings = {
    dark: "true"
  }
#+END_SRC

The pattern it self is just really extra boilerplate we don't need.
Another history complete if we we're using C++.

** Prototype
Just a fancy word for **clone**.

The problem it aims to solve is Inheritance hell, like:
#+BEGIN_SRC typescript
  class Animal {}

  class Dog extends Animal {}
  class Cat extends Animal {}
  // ...
#+END_SRC

Prototype pattern is an alternative way to implement inheritance, but
not by classes.

Intead it inherites by objects that have already been created.

#+BEGIN_SRC typescript
  const zombie = {
    eatBrains() {
      return "I like brains";
    }
  }

  const chat = Object.create(zombie, {name: { value: "chad" }});

  console.log(chad); // {name: 'chad'}   where is the method?

  chad.eatBrains(); // "I like brains"  js goes up the prototype chain

  chad.__proto__; // gets the prototype, but not the modern best pratice
  Object.getPrototypeOf(chad);
#+END_SRC

When it comes to classes in JS, prototype reffers to its constructor.
That means we can extend a class with aditional functions if we want
to. But this is also generally considerated a bad pratice.

#+BEGIN_SRC typescript
  Array.prototype.bad = function() {
    console.log("im bad");
  }

  [].bad() // "im bad"
#+END_SRC

** Builder
Imagine you're running a hot-dog stand and when a custumer asks you an
order they need to tell you everything they want in their sandwich in
the constructor.

#+BEGIN_SRC typescript
  class HotDog {
    constructor (
      public bun: string,
      public ketchup: boolean,
      public mustard: boolean,
      public kraut: boolean
    ) { }
  }

  new HotDog('wheat', flase, true, true);
#+END_SRC

It works but it gets hard to follow e we might want to deffer one
step or other for later.

An alternative is to build the object step by step using methods and
not the constructor. This is the builder pattern.

#+BEGIN_SRC typescript
  class HotDog {
    constructor (
      public bun: string,
      public ketchup?: boolean,
      public mustard?: boolean,
      public kraut?: boolean
    ) {}

    addKetchup() {
      this.ketchup = true;
      return this;
    }

    addMustard() {
      this.mustard = true;
      return this;
    }

    addKraut() {
      this.kraut = true;
      return this;
    }
  }

  const myLunch = new HotDog('gluten free')

  myLunch
    .addKetchup()
    .addMustard()
    .addKraut();  // wow, it allows method chaining!
#+END_SRC

** Factory
Insted of using the `new` keyword to instantiate an object you use a
function or method to do it for you.

Imagine you're making a cross platform app that runs on Androind and
Ios.

Without factory:
#+BEGIN_SRC typescript
  class IOSButton { }
  class AndroidButton { }

  const button1 = os === "ios" ? new IOSButton() : new AndroidButton();
  const button2 = os === "ios" ? new IOSButton() : new AndroidButton();  
#+END_SRC

Now with the factory:
#+BEGIN_SRC typescript
  class ButtonFactory {
    createButton(os: string): IOSButton | AndroidButton {
      if (os === "ios") {
	return new IOSButton();
      } else {
	return new AndroiButton();
      }
    }
  }

  const factory = new ButtonFactory();  // << this is the factory
  const btn1 = factory.createButton(os);
  const btn2 = factory.createButton(os); // smart object creation
#+END_SRC

* Structural
How objects relate to each other
** Facade
Facade is basically a simplified API to hide another low level details in
your codebase

#+BEGIN_SRC typescript
  class PlumbingSystem {
    // Low level access to plumbing system
    setPressure(v: number) {}
    turnOn() {}
    turnOff() {}
  }

  class ElectricalSystem {
    // Low level acces to electrical system
    setVoltage(v: number) {}
    turnOn() {}
    turnOff() {}
  }

  class House {  // Simplified wrapper
    private plumbing = new PlumbingSystem();
    private electrical = new ElectricalSystem();

    public turnOnSytems() {
      this.electrical.setVoltage(120);
      this.electrical.turnOn();
      this.plumbing.setPressure(500);
      this.plumbing.turnOn();
    }

    public turnOffSytems() {
      this.electrical.turnOff();
      this.plumbing.turnOff();
    }
  }

  const client = new House();
  client.turnOnSystems();
  client.turnOffSystems();
#+END_SRC

Almost Every package on JS is a facade, like jQuery.

** Proxy
A fancy word for substitute.

You can replace a target object with a proxy.

A greate case study would be reactivity system in Vue JS.

You create data, but the framework itself needs a way of intercept
that data and update the UI whenever the data changes.

The way Vue does is substituting the original object with a proxy.

#+BEGIN_SRC typescript
  const original = { name: "Jeff" };

  const reactive = new Proxy(original, {
    get(target,key) {
      console.log("Tracking: ", key);
      return target[key];
    },
    set(target, key, value) {
      console.log("updating UI...');
      return Reflect.set(target, key, value);
    },
  });


  reactive.name;         // logs: 'tracking name'
  reactive.name = "bob"  // logs: 'updating the ui'

#+END_SRC

Proxys are also used when you have very large objects that would be
too expensive to duplicate in memory.

* Behavioral
How objects communicate with each other
** Iterator
Allows you to triverse through a collection of objects.

Modern languages already provides abstractions for the iterators, like:

#+BEGIN_SRC typescript
  const cart = ["apple", "banana", "orange"];

  for (const item of cart) {
    console.log(item);
  }
#+END_SRC

We can also make the non-build in `range` function like:

#+BEGIN_SRC typescript
  function range(start, end, step=1) {
    return {
      [Symbol.iterator]() { // Allows to use in regular for loop
	return this;
	},
      next() {             
	if (start < end) {
	  start = start + step;
	  return { value: start, done: false };
	}
	return { done: true, value: end };
      }
    }
  }

  for (const n of range(0, 20, 5)) {   // logs: 5, 10, 15, 20 on each line
    console.log(n);
  }

  console.log([...range(0, 10)]); // logs: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
#+END_SRC


With iterator you start with a collection and write some code that
determines how to get from the beginning to the end.

It is a pull-based systems.
** Observer
A push-base system.

The observer pattern allows many objects to subscribe to events
broacasted by another object.

It is a `one-to-many` relationship.

It is used in places like `firebase` where when your data is changed
on the saver, the clients subscribed to it are automatically updated
with the latest changes.

#+BEGIN_SRC typescript
  import { Subject } from "rxjs";

  const news = new Subject();

  const tv1 = news.subscribe( v => console.log(v + "via net tv"));
  const tv2 = news.subscribe( v => console.log(v + "via another tv"));
  const tv3 = news.subscribe( v => console.log(v + "via even another tv"));


  // to push a new value to the subject
  news.next("Breaking news: ");
  news.next("The war is over ");
#+END_SRC

You can think of it like a for loop that unfolds over the dimention of
time.

** Mediator
A mediator is like a middleman or a broker.

We have a many to many relationship.

#+BEGIN_SRC typescript
  class Airplane {

    }

  class Runway {
    clear: boolean;
    }

  const runway25A = new Runway();
  const runway25B = new Runway();
  const runway7 = new Runway();
  const a = new Airplane();
  const b = new Airplane();
  const c = new Airplane();


  // In order to provide coordination and communication

  class Tower {
    clearForLanding(runway: Runway, plane: Airplane) {
      if (runway.clear) {
	console.log(`Plane ${plane} is clear for landing`);
      }
    }
  }
#+END_SRC

A more practical example. In the express JS web framework, there's a
middleware system.

#+BEGIN_SRC typescript
  import express from "express";
  const app = express();

  function logger(req, res, next) {
    console.log("Request Type: ", req.method)
    next()
  }

  app.use(logger);

  app.get("/", (req, res) => {
    res.send("Hello World");
  });
#+END_SRC

It provides separation of concerns and eliminates code duplication.

** State
An object behaves different based on a finite number of states.

In your code you possible use conditional logic or switch statements
to handle a bunch of possibilities base on the state or data on your
application.

Example:

#+BEGIN_SRC typescript
  class Human {
    think(mood) {
      switch(mood) { // Switch Hell
	case "happy":
	  return "I am happy! :)";

	case "sad":
	  return "I am sad! :(";

	default:
	  return "I am neutral :|";
      }
    }
  }
#+END_SRC

The problem is that this kind of code, usually don't scale very well.

The state pattern allows you to start with one base class then provide different functionality based on it internal state.

The idea comes from **Finite State Machines** and libraries like XState.

Another way to go with the provided example:

#+BEGIN_SRC typescript
  interface State {
    think(): string;
  }

  class HappyState implements State {
    think() {
      return "I am happy! :)";
    }
  }

  class SadState implements State {
    think() {
      return "I am sad! :(";
    }
  }

  class NeutralState implements State {
    think() {
      return "I am neutral! :|";
    }
  }

  class Human {
    state: State;

    constructor() {
      this.state = new HappyState();
    }

    think() {
      return this.state.think();
    }

    changeState(state) {
      this.state = state;
    }

  }
#+END_SRC
